### ISSUE TITLE
为啥在我本地虚拟机上感觉不到变快

### ISSUE THREAD

**Issue by humour-picasso** [liufee/yii2-swoole#13]
我进行了这个测试，为啥在我本地虚拟机上感觉不到变快呢？是我什么地方做错了吗
访问80端口是在php-fpm，访问9998端口就是在swoole上了吗？

**Comment by bijiaxing6** [comment]
这是测试结果，并没有明显变快
---------------------------------swoole-----------------------------
./wrk -c 100 -t 4 -d 10 --latency http://tictic-op.local.com:9998
Running 10s test @ http://tictic-op.local.com:9998
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12s   543.92ms   1.98s    53.85%
    Req/Sec    23.55     13.70    40.00     54.22%
  Latency Distribution
     50%    1.12s 
     75%    1.55s 
     90%    1.84s 
     99%    1.98s 
  264 requests in 10.02s, 21.38MB read
  Socket errors: connect 0, read 0, write 0, timeout 212
  Non-2xx or 3xx responses: 264
Requests/sec:     26.34
Transfer/sec:      2.13MB
---------------------------------php-fpm-----------------------------
./wrk -c 100 -t 4 -d 10 --latency http://tictic-op.local.com
Running 10s test @ http://tictic-op.local.com
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.58s   260.63ms   1.91s    60.00%
    Req/Sec    10.57      6.71    30.00     71.62%
  Latency Distribution
     50%    1.53s 
     75%    1.86s 
     90%    1.91s 
     99%    1.91s 
  104 requests in 10.02s, 7.10MB read
  Socket errors: connect 0, read 0, write 0, timeout 94
Requests/sec:     10.38
Transfer/sec:    725.30KB
