### ISSUE TITLE
启动时出错。

### ISSUE THREAD

**Issue by GordonHuangYong** [liufee/yii2-swoole#17]
$ php  ./yii swoole/start

Exception 'Error' with message 'Class 'swoole_http_server' not found'

in /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/feehi/yii2-swoole/src/swoole/SwooleServer.php:26

Stack trace:
#0 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/feehi/yii2-swoole/src/console/SwooleController.php(97): feehi\swoole\SwooleServer->__construct('127.0.0.1', 9999, 1, 1, Array, Array)
#1 [internal function]: feehi\console\SwooleController->actionStart()
#2 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('start', Array)
#5 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('start', Array)
#6 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('swoole/start', Array)
#7 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('swoole/start', Array)
#8 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /Volumes/Macintosh HD/Users/fushi/Documents/huangyong/eclipse/feehicms/yii(27): yii\base\Application->run()
#10 {main}

**Comment by purevirtual** [comment]
这是你没装好swoolez造成的
