### ISSUE TITLE
无法正常打印yii2.log

### ISSUE THREAD

**Issue by purevirtual** [liufee/yii2-swoole#24]
看了下文档和源码 也扫了下示例工程 https://github.com/liufee/cms 但是里面都没有可打印原来yii2 log的地方 应该是需要额外的开发logger组件 而作者没有开发？

**Comment by purevirtual** [comment]
已解决 发现日志都在console底下
推荐一篇文章 可以很好的解决swoole+yii2的log问题 https://zguoqiang.com/2018/12/17/swoole%E5%9F%BA%E7%A1%80-%E4%B8%8E%E4%BC%A0%E7%BB%9FMVC%E6%A1%86%E6%9E%B6%E7%9A%84%E6%95%B4%E5%90

**Comment by liufee** [comment]
感谢，但是yii2不适合在swoole上跑，所以已经停止维护了。可以加入群，让他做的更好

**Comment by purevirtual** [comment]
> 感谢，但是yii2不适合在swoole上跑，所以已经停止维护了。可以加入群，让他做的更好

恩 我这两个星期看完了swoole的资料 还有yii2-swoole的几个扩展 确实yii2设计的时候默认是单实例的 所以多实例的时候一些方法就会有问题 比如Yii::info其实调的是主进程的方法
所以 作者现在是在用swoft?

**Comment by purevirtual** [comment]
#25 已经在这里进行了改进
